theme: jekyll-theme-slate
title: <a href="https://ruindig.github.io"><span style="color:white">Page-RuinDig</span></a>
description: RuinDigのポートフォリオページ｜Posts are my own.
twitter:
  username: RuinDig
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /RuinDig.jpg
exclude:
  - templates
  - assets
  - _layouts
  - _includes
  - .vscode
  - hook.js
  - _config.yml
  - README.md