theme: jekyll-theme-slate
title: Page-RuinDig
description: RuinDigのポートフォリオページ｜Posts are my own.
twitter:
  username: RuinDig
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /RuinDig.jpg
