theme: jekyll-theme-slate
title: <span style="white"><a href="https://ruindig.github.io">Page-RuinDig</a></span>
description: RuinDigのポートフォリオページ｜Posts are my own.
twitter:
  username: RuinDig
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /RuinDig.jpg
